version: '3.9'
networks: 
  app-network: 
    driver: bridge
services:
  php: 
    container_name: php
    build: 
      context: .docker/local/
      dockerfile: php.dockerfile
    volumes: 
      - .:/var/www/html
    ports: 
      - 9000:9000
    networks: 
      - app-network
  db:
    container_name: db
    image: postgres:17.3-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .docker/local/data/:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
